### ISSUE TITLE
White line when plotting with polar stereo projections

### ISSUE THREAD

**Issue by ackerlar** [FESOM/pyfesom#13]
Hi,
I am trying to plot FESOM1.4 with in a SouthPolarStereo projection and get this white line at one meridian, similar to what you have mentioned here, @koldunovn : https://github.com/koldunovn/pi_mesh_python/blob/master/triangular_mesh_maps_NorthPolarStereo.ipynb

I was just wondering, where to get the *.txt from (elements.txt, xnodes.txt, etc.) as they seem to be crucial for getting rid of this white line. Or are there other ways to accomplish that? Could someone maybe clarify this?

**Comment by koldunovn** [comment]
I use those names in the examples to make things easier for uninitiated (not FESOM users). It's just usual nodes and elements. In case of pyfesom mesh object:

```
xnodes = mesh.x2
ynodes = mesh.y2
elem   = mesh.elem
```

**Comment by ackerlar** [comment]
Thank you! I didn't think it would be so easy. However, when I use `mesh.elem` instead of `elem_no_nan[::]`, `m.drawmapboundary()` does not work properly as the continent is not shown anymore.

without `mesh.elem`:
![1pctAnt5_omldamax](https://user-images.githubusercontent.com/72916819/107428183-8fc45180-6b22-11eb-9c3f-706d104ad708.png)

with `mesh.elem`:
![1pctAnt5_omldamax__](https://user-images.githubusercontent.com/72916819/107428122-7e7b4500-6b22-11eb-92e1-738406dfae1c.png)

But I guess it is a Basemap issue, then.

**Comment by koldunovn** [comment]
Yes. Maybe Basemap tries to interpolate over, so the "fix" is just to overlay the continent.
BTW the part of the issue I describe in this notebook is being solved in cartopy (https://github.com/SciTools/cartopy/issues/1345). I wouldn't stick to Basemap for very long, it's not supported anymore :(

**Comment by ackerlar** [comment]
Okay, thank you! I will close this issue then.
