### ISSUE TITLE
problems with processing velocity data

### ISSUE THREAD

**Issue by auroralin0408** [FESOM/pyfesom#17]
I did't find examples about processing FESOM velocity data using pyfesom, and I met some problems I coudn't figure out:
1. `u, elem_no_nan = pf.get_data(f.variables['u'][time_id,:],mesh,lv_dep)`
the output u is 2-d, not like temp whose output is 1-d and is the same size as mesh.x2. What's the corresponding grid of the u? 
2. If I use `pf.fesom2regular(u, mesh, lonn, latt, how='idist', k=10)` directly, is the output right for me to use in lon/lat grid? Is there a need to use `pf.vec_rotate_r2g` ?

**Comment by koldunovn** [comment]
Hi

Are you trying to use FESOM1.4 data (e.g. CMIP6 output) or FESOM2?
In the first case I would need an example of files, since there might be differences in output formats.

The answer to the second question is probably yes, as the output in most of the cases is on rotated grid.

**Comment by auroralin0408** [comment]
Thanks for your quick reply! @koldunovn 
I'm using FESOM 1.4 data, and I just found out what's wrong with my code that led to the first question...

As for the second question, should I use `pf.vec_rotate_r2g` after `pf.get_data` and before `pf.fesom2regular`, and plot with u_idw? or there is no need to use `pf.fesom2regular`, and I can interpolate u1 on my own and plot the results?
![image](https://user-images.githubusercontent.com/118411170/202598712-40acee1b-0d05-4401-bdd7-77af6539a6d7.png)

**Comment by auroralin0408** [comment]
And, if I want to plot  the w, is the process the same as plotting temp and no need for `pf.vec_rotate_r2g` ?

**Comment by koldunovn** [comment]
@auroralin0408 you have to get the data and then rotate, yes. You can then interpolate or plot original data on triangular mesh, this choice is on you :) You can totally interpolate U1 by yourself with the method you find best.

**Comment by auroralin0408** [comment]
ok, I understand. Thanks a lot!
